[package]
name = "monovault"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuse_mt = "0.5.1"
serde = "1.0.137"